org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.94

mod_id=unplugged_afk
mod_name=Unplugged AFK
mod_license=LGPL-3.0-only
mod_version=0.1.0-alpha.3+mc26.1.2
mod_group_id=com.theonlytazz.unpluggedafk

curseforge_project_id=1646152
curseforge_project_slug=unplugged-afk
